### ISSUE TITLE
你这个真的实现了通信了吗？

### ISSUE THREAD

**Issue by laopaoerdudu** [kongpf8848/aidldemo#1]
你这个 demo 根本就不可以用，

**Comment by kongpf8848** [comment]
可以的，可能是你的使用姿势不对。先运行aidlserver程序，再运行aidlclient程序，然后点击客户端绑定服务按钮，然后双方就可以发送图片了，为了保证客户端和服务端进程同时存在，你可以开启分屏功能，在一个窗口里同时展示客户端和服务端界面。
